language: android
jdk: oraclejdk8
android:
  components:
  - extra-android-support
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository  
  - tools
  - platform-tools
  - build-tools-24.0.1
  - android-24
licenses:
    - '.+'
script:
  - echo "<?xml version=\"1.0\" encoding=\"utf-8\"?><resources><string name=\"google_map_key\">AIzaSyCLTYgwKb_e8pTGnx21ZrH0I67LQdojMZk</string></resources> " > app/src/main/res/values/secrets.xml
  - ./gradlew assembleDebug 
